name: Mendels Sheeps
version: 0.4
author: Mort
main: mort.mendelsheep.MendelSheep
load: startup
commands:
    mendelsheep:
        usage: /<command>
        aliases: [ ms ]
        permissions: mendelsheep.spawn